export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_FAV_CONTACTS = 'GET_FAV_CONTACTS';
export const GET_CONTACT_BY_ID = 'GET_CONTACT_BY_ID';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const INSERT_CONTACTS = 'INSERT_CONTACTS';
